### ISSUE TITLE
Even though I followed the tutorial completely, I still had bugs

### ISSUE THREAD

**Issue by Erriyue** [emre1702/altv-CustomCommandsSystem#1]
[22:51:31] < ==== UNHANDLED EXCEPTION ==== > 

 Received an unhandled exception from: System.NullReferenceException: Object reference not set to an instance of an object.

   at CustomCommandsSystem.Common.Utils.AltAsyncUtils.DoConsideringTest(Action action)

   at CustomCommandsSystem.Services.Executer.MethodExecuter.RunSync(CommandMethodData methodData, Object[] args)

   at CustomCommandsSystem.Services.Executer.MethodExecuter.TryExecuteSuitable(IPlayer player, UserInputData userInputData, CommandData commandData, List`1 possibleMethods)

   at CustomCommandsSystem.Services.CommandsHandler.ExecuteCommand(IPlayer player, String message)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)

   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Could you help me?

**Comment by emre1702** [comment]
Hello, sorry for the late response, didn't see your question.
![image](https://user-images.githubusercontent.com/15148761/139576304-35caeceb-61ce-4de6-9c16-c4fad92ada04.png)
Did you implement it in an AsyncResouce?

**Comment by Erriyue** [comment]
Thank you for your reply, although I have already done this with my code  👍
